spring.application.name=api_events
server.port=8080

spring.datasource.url = jdbc:postgresql://localhost:5432/db_events
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.schemas=api_events
spring.flyway.default-schema=api_events
spring.flyway.locations=classpath:db/migration

spring.jpa.properties.hibernate.default_schema=api_events

jwt.secret=Who-hack-is-gay